export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"; 
  
// Swiggy API to get Restaurant data with corsproxy
export const swiggy_api_URL =
  "https://corsproxy.io/?https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.1702401&lng=72.83106070000001&page_type=DESKTOP_WEB_LISTING";

// menu items api card type key
export const MENU_ITEM_TYPE_KEY = "type.googleapis.com/swiggy.presentation.food.v2.ItemCategory";
export const RESTAURANT_TYPE_KEY = "type.googleapis.com/swiggy.presentation.food.v2.Restaurant";
export const resturantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "82972",
        name: "Burger King",
        uuid: "3a05e4cc-27d5-4376-ab35-ca1034a00b11",
        city: "11",
        area: "Sector 20",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "28fb13049b4e55297bb3f703cde63c35",
        cuisines: ["Burgers", "American"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 4.699999809265137,
        slugs: {
          restaurant: "burger-king-panchkula-sector-20-panchkula",
          city: "chandigarh",
        },
        cityState: "11",
        address:
          "Burger King India Pvt. Ltd.SCO. No.406, Ground floor, Panchkula Sector-20, Panchkula, Haryana-134116.",
        locality: "Sector 20",
        parentId: 166,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT120 off",
          shortDescriptionList: [
            {
              meta: "FLAT120 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT120 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹120 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT120 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3600,
          message: "",
          title: "Delivery Charge",
          amount: "3600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6524170~p=1~eid=00000187-99d6-ba5d-285e-099200b10154",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "82972",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 4.699999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "253998",
        name: "McDonald's",
        uuid: "1187a7a1-d2d5-4a73-aeb7-b268647d3138",
        city: "11",
        area: "Sector 19",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "1293a58ab5610f4c730c3d8cb6ac1b65",
        cuisines: ["American"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant:
            "mcdonalds-punjab-zirakpur-paras-down-town-mall-greater-mohali",
          city: "chandigarh",
        },
        cityState: "11",
        address:
          "Punjab Zirakpur Paras, Shop No. GF- 01 ,Paras Down Town Square, Village Zirakpur,  Tehsil Derabassi, District Mohali. Punjab-140603",
        locality: "Paras Downtown Square Mall",
        parentId: 630,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "253998",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "51643",
        name: "Sagar Ratna",
        uuid: "c1e5dbe5-5136-4f85-84a6-e2ddd024d103",
        city: "11",
        area: "Sector 19",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "eogphguaixson8bvrvcf",
        cuisines: ["North Indian", "South Indian", "Punjabi"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "sagar-ratna-sector-19-panchkula",
          city: "chandigarh",
        },
        cityState: "11",
        address: "SCO 14, Kalagidhar Enclave, Baltana, Sector 19, Panchkula",
        locality: "Kalagidhar",
        parentId: 793,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Flat ₹125 off",
          shortDescriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6498727~p=4~eid=00000187-99d6-ba5d-285e-099300b10419",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "51643",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "361958",
        name: "Pizza Hut",
        uuid: "371667d1-e382-48ea-a58d-31ee81422849",
        city: "11",
        area: "Baltana Zirakpur",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "pizza-hut-baltana-zirakpur-test_area-panchkula",
          city: "chandigarh",
        },
        cityState: "11",
        address:
          "PIZZA HUT at SCO- 7, Kalgidhar Enclave, Shimla Highway, Baltana, Zirakpur, Mohali, Punjab-140604",
        locality: "Kalgidhar Enclave",
        parentId: 721,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Free Pepsi Pet Bottle",
          shortDescriptionList: [
            {
              meta: "Free Pepsi Pet Bottle on orders above ₹249",
              discountType: "Freebie",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Free Pepsi Pet Bottle on orders above ₹249",
              discountType: "Freebie",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Pepsi Pet Bottle",
              discountType: "Freebie",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Free Pepsi Pet Bottle on orders above ₹249",
              discountType: "Freebie",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "361958",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.4",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "390283",
        name: "Punjabi chulha",
        uuid: "66c0b297-38ef-47d4-ae0a-fe467cc68725",
        city: "11",
        area: "Zirakpur",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "utf0cwqwzgxjdse5twi2",
        cuisines: [
          "North Indian",
          "South Indian",
          "Chinese",
          "Chaat",
          "Beverages",
          "Ice Cream",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "punjabi-chulha-zirakpur-zirakpur",
          city: "chandigarh",
        },
        cityState: "11",
        address:
          "SHOP. 21,PARAS DOWNTOWN SQUARE,NEAR PANCHKULA CROSSING ZIRAKPUR,DERA BASSI, Ajitgarh, MOHALI,Punjab - 140603",
        locality: "Paras Downtown Square",
        parentId: 2591,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "10% off",
          shortDescriptionList: [
            {
              meta: "10% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "10% off up to ₹40 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "10% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "10% off up to ₹40 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "390283",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.4",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "40359",
        name: "Shirdi Food & Snacks",
        uuid: "c03595f5-6532-4687-95d7-98e6a68c48d6",
        city: "11",
        area: "Manimajra",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "f4a6db4d707152b765950d9bb4cd0f47",
        cuisines: [
          "North Indian",
          "Punjabi",
          "Indian",
          "Chinese",
          "Desserts",
          "Snacks",
          "Fast Food",
          "Tandoor",
          "Biryani",
          "Pan-Asian",
          "Thalis",
          "Hyderabadi",
          "Chaat",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 8.600000381469727,
        slugs: {
          restaurant: "shirdi-food-snacks-manimajra-manimajra",
          city: "chandigarh",
        },
        cityState: "11",
        address:
          "#2254/H, 1st Floor, Above Muthoot Finance, Pipliwala Town, Manimajra, Chandigarh",
        locality: "Manimajra",
        parentId: 183112,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Flat ₹125 off",
          shortDescriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6500,
          message: "",
          title: "Delivery Charge",
          amount: "6500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6497563~p=7~eid=00000187-99d6-ba5d-285e-099400b1072a",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "40359",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 8.600000381469727,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "85289",
        name: "The South Xpress",
        uuid: "14905013-6182-4285-8ff2-fe332eb2240b",
        city: "11",
        area: "Sector 19",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "yb05mflimdyuvd7y3t21",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "the-south-xpress-baltana-zirakpur",
          city: "chandigarh",
        },
        cityState: "11",
        address: "SCO 14, Kalgidhar Enclave, Baltana, zirakpur",
        locality: "Baltana",
        parentId: 214084,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Flat ₹125 off",
          shortDescriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹125 OFF",
          shortDescriptionList: [
            {
              meta: "Use MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹125 off on orders above ₹199 | Use code MATCHDEAL125",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "special",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "HEAVY",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "85289",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "HEAVY",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
  ]; 